# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
  - cron: "15 9 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  clean_db:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Clean database.json
      run: |
        echo
        "{
          "users": [
            {
              "id": 1,
              "username": "niklauswirth89",
              "email": "nw89@pascal.cre",
              "password": "thePascalP10n33r>2024-01-01",
              "firstname": "Niklaus",
              "lastname": "Wirth",
              "age":89
            }
          ],
          "posts": []
        }" > ./week11/auth/json-server/database.json
